jp7677/dxvk-nvapi

src/sysinfo/nvapi_adapter.cpp
src/sysinfo/nvapi_adapter.h
src/util/util_op_code.h

One thought that came up is whether it's better to allocate `m_deviceExtensions` like we currently are, or if it would make more sense to use `std::vector` here so that `~NvapiAdapter()` can remain trivial. What's your preference on this @jp7677 ?

Query and store supported Vulkan Device Extensions in NvapiAdapter

---

src/nvapi.cpp
src/nvapi_private.h

Fairly straightforward (but not very performant) solution to initialization refcounting issue.
Fixes #16.

Count initializations, guard `Initialize` and `Unload` with a mutex

---

src/nvapi_gpu.cpp
src/nvapi_interface.cpp
src/sysinfo/nvapi_adapter.cpp
src/sysinfo/nvapi_adapter.h
src/sysinfo/nvml.cpp
src/sysinfo/nvml.h
tests/nvapi_sysinfo.cpp
tests/nvapi_sysinfo_mocks.cpp
tests/nvapi_system.cpp

These two NvAPI functions provides the needed info for Unigine Heaven and Unigine Vulkan to display gpu/mem frequency aswell as temperatures.
There does not seem as any way to get voltages from nvml atm.

Implement NvAPI_GPU_GetPstates20 and NvAPI_GPU_GetCurrentPstate

---

src/nvapi.cpp
src/nvapi_d3d.cpp
src/nvapi_d3d11.cpp
src/nvapi_d3d12.cpp
src/nvapi_disp.cpp
src/nvapi_gpu.cpp
src/nvapi_sys.cpp

Improves logging a bit by removing hard-coded strings for function
names.
Uses __func__ due to its being portable and accessible in all the
compilers after 90s, while __FUNCTION__ isn't portable and is a gnu
extension, and we know we build the project with more or less modern
compilers. The __PRETTY_FUNCTION__ isn't used as we only need to have a
function name printed out.

nvapi: Use __func__ macro for function names.

---

build-win32.txt
build-win64.txt

Without doing this with Meson 0.49 we get:
linker = self.cross_info.config['binaries']['ar']
KeyError: 'ar'
This is fixed in newer Meson releases but Proton's build system is based
on Steam's Soldier runtime that will be stuck on 0.49 for a while.

build: Specify ar in the cross files

---

src/nvapi_d3d12.cpp

Change the logging behavior for NvAPI_D3D12_CreateCubinComputeShader to
distinguish from NvAPI_D3D12_CreateCubinComputeShaderWithName. This
matches the logging behavior for the functions of similar names for
NvAPI_D3D11.

nvapi-d3d12: Improve logging for NvAPI_D3D12_CreateCubinComputeShader

---

src/sysinfo/nvapi_adapter.cpp
src/sysinfo/nvapi_adapter.h
src/sysinfo/nvapi_adapter_registry.cpp
src/sysinfo/resource_factory.cpp
src/sysinfo/resource_factory.h
tests/mock_factory.cpp
tests/nvapi_sysinfo.cpp
tests/nvapi_sysinfo_mocks.cpp
tests/nvapi_sysinfo_util.cpp

We would need this for creating a D3D12Device for querying feature support.
This is supported since Win7, so safe to do.

nvapi-adapter: Update to DXGIAdapter1

---

src/nvapi.cpp
src/nvapi_drs.cpp
src/nvapi_gpu.cpp
src/nvapi_sys.cpp
src/util/util_string.cpp
src/util/util_string.h

DXVK_NVAPI_VERSION comes from the VCS tag, we should not asume that it is always short. The same applies for adapter and display names.
Fixes https://github.com/jp7677/dxvk-nvapi/issues/76

nvapi: Copy into NVAPI-Shortstring without writing out of bounds

---

src/nvapi_private.h

Fixes build errors on GCC 12.
By the way, we should also fix this:
```
[1/38] Generating version.h with a custom command
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /github/workspace
```
…, otherwise builds from GH Actions could report unexpected version to callers.

includes: Add missing standard library includes

---

src/sysinfo/nvml.cpp
src/sysinfo/nvml.h
tests/nvapi_system.cpp

As discussed earlier. Vulkan (and LFX) stuff remains untouched because there's not much to be gained there.
A minor change to `GETPROCADDR` allowed me to also get rid of `template <typename T> T GetProcAddress(…)`.

Macro magic

---

inc/nvml.h
src/nvapi_gpu.cpp
tests/nvapi_sysinfo.cpp

NVML header from release 515.65.01 has the signedness of `int`s in `nvmlGpuThermalSettings_t` fixed, so we can remove our hackish reinterpret cast now.

nvapi-gpu: Remove temperature signedness workaround

---

src/sysinfo/nvapi_adapter.cpp
src/sysinfo/nvapi_adapter.h
src/sysinfo/vulkan.cpp
src/sysinfo/vulkan.h
tests/nvapi_sysinfo.cpp
tests/nvapi_sysinfo_mocks.h
tests/resource_factory_util.cpp
tests/resource_factory_util.h

This way we honor DXVK memory overrides from DXVK configuration.

nvapi-adapter: Report vram size based on DXGI adapter

---

src/resource_factory.cpp
src/resource_factory.h
src/sysinfo/nvapi_adapter.cpp
src/sysinfo/nvapi_adapter.h
src/sysinfo/nvapi_adapter_registry.cpp
src/sysinfo/nvapi_adapter_registry.h
tests/mock_factory.h

Just free the resources, including the DXGIFactory, once we have all the info we need. Also use the existing DXGIFactory to obtain the Vulkan entry points.
@Saancreed  Any thoughts on this? In my opinion it is less clean, but freeing the resources once we don't need them anymore feels good too.

nvapi-adapter: Free Vulkan after adapter initialization

---

src/nvapi_gpu.cpp
src/util/util_env.cpp
src/util/util_env.h
tests/nvapi_sysinfo.cpp

Lets see how we get away for The Last Of Us...
Return OK for GetGpuCoreCount, GetAllClockFrequencies and GetPstates20 when detecting The Last of Us part 1. Otherwise this title wont start.

nvapi-gpu: Fake several NVML related methods

---

src/nvapi_gpu.cpp

No need to initialize everything for the-last-of-us. 
Much less code and also addresses a justified review comment from the initial work around. Waiting for confirmation ...
(Follow up from https://github.com/jp7677/dxvk-nvapi/pull/117)

nvapi-gpu: Simplify work around

---

src/nvapi.cpp
src/nvapi_gpu.cpp
tests/nvapi_sysinfo.cpp

It doesn't allow hardware PhysX in https://github.com/jp7677/dxvk-nvapi/issues/127, but at least it doesn't crash anymore.
The header says:
```c
typedef struct _NV_COMPUTE_GPU_TOPOLOGY_V2
{
NvU32 version;                 //!< Structure version
NvU32 gpuCount;                //!< Size of array
NV_COMPUTE_GPU *computeGpus;   //!< Array of compute-capable physical GPUs (allocate memory of size of Physical gpuCount of system).
} NV_COMPUTE_GPU_TOPOLOGY_V2;
```
I would interpret it that this has to be done on the consumer side, but here we are...

Prevent CudaEnumComputeCapableGpus V2 crash

---

src/d3d/lfx.h
src/util/util_log.cpp

This mirrors what DXVK and VKD3D-Proton does for printing to console (https://github.com/doitsujin/dxvk/commit/05fb634f9102f18e6a2c9e84939d0fb0a3618671) and also fixes lost console output on Wine 8.12.

Use __wine_dbg_output for console output

---

src/nvapi_d3d12.cpp
tests/nvapi_d3d12.cpp

We should keep games built against older NVAPI working, so instead of failing when encountering unexpected `geometryDescStrideInBytes` (like, when using NVAPI headers from before 535 in which DMMs were added causing the union to grow) this will try to access array members by manually calculating their address (and this will now keep working without rebuilding or updating headers if another union member is added in the future).
Adding tests this led me to discover a bug where we assume that after `NvAPI_D3D12_GetRaytracingAccelerationStructurePrebuildInfoEx` / `NvAPI_D3D12_BuildRaytracingAccelerationStructureEx` returns, we can still read values from pointer passed in `pGeometryDescs` which is not the case (because it points to data of a `std::vector` living on the stack of called …

Some DMM-related fixes and improvements

---

src/d3d11/nvapi_d3d11_device.cpp
src/d3d11/nvapi_d3d11_device.h
src/d3d12/nvapi_d3d12_device.cpp
src/d3d12/nvapi_d3d12_device.h
src/nvapi_disp.cpp
src/sysinfo/nvapi_adapter_registry.cpp
tests/nvapi_d3d11.cpp
tests/nvapi_d3d12.cpp
tests/nvapi_sysinfo.cpp
tests/nvapi_tests_private.h
tests/resource_factory_util.cpp

This should especially improve test isolation.

Invalidate cache maps

---

src/nvapi_gpu.cpp
src/sysinfo/nvapi_adapter.cpp
src/sysinfo/nvapi_adapter.h
src/sysinfo/nvapi_output.cpp
tests/nvapi_sysinfo.cpp

Not that cool to do this, but seems to help to use LatencyFlex on AMD GPUs with Streamline because `NvAPI_GPU_GetArchInfo` no longer fails.
There shouldn't be any side effects since DLSS requires at least Turing.

Spoof Pascal for non-NVIDIA propietary driver

---

src/nvapi_gpu.cpp

The version needs to be checked before accessing any fields from the struct.
The tests for incompatible struct versions left the pOSAdapterId uninitialized, which caused flakes on MSVC. This fixes it.

nvapi-gpu: Validate version before accessing struct fields

---

.github/workflows/build-test-package-linux.yml
.github/workflows/build-test-windows.yml
README.md
dependabot.yml

It's long overdue to update the README usage guide.
While at it, also some smaller CI changes...

meta: Update usage section

---

src/d3d/nvapi_d3d_instance.cpp
src/d3d/nvapi_d3d_instance.h
src/d3d/nvapi_d3d_low_latency_device.cpp
src/d3d/nvapi_d3d_low_latency_device.h
src/d3d12/nvapi_d3d12_device.cpp
src/d3d12/nvapi_d3d12_device.h
src/meson.build
src/nvapi_d3d.cpp
src/nvapi_d3d12.cpp
src/nvapi_interface.cpp
src/shared/shared_interfaces.h
src/sysinfo/nvapi_adapter_registry.cpp
src/vkd3d-proton/vkd3d-proton_interfaces.h
tests/meson.build
tests/nvapi_d3d.cpp
tests/nvapi_d3d12.cpp
tests/nvapi_d3d12_mocks.h
tests/nvapi_d3d_mocks.h
tests/nvapi_tests_private.h

The intent of this PR is to enable Reflex for all D3D11, and D3D12 titles using dxvk-nvapi. It does this through a new device interface called ID3DLowLatencyDevice, which will be exposed from vkd3d-proton, and dxvk.
To provide compatibility with LatencyFleX this change will only use the ID3DLowLatencyDevice interface when LatencyFleX is not detected.

Add support for Reflex

---

.github/workflows/build-test-package-linux.yml

It's getting outdated. The original project hasn't seen much activity either :(.

ci: Remove gcc problem matcher

---

README.md
src/sysinfo/nvapi_adapter.cpp
tests/nvapi_sysinfo.cpp

Reporting Mesa version numbers turned out to be not very useful.
@Saancreed Any thoughts?

sysinfo: Report 999.99 as version for  non-NVIDIA proprietary driver

---

src/d3d/nvapi_d3d_low_latency_device.cpp
src/nvapi_d3d.cpp
src/nvapi_d3d12.cpp
tests/nvapi_d3d.cpp
tests/nvapi_d3d12.cpp

Fixes a crash in Horizon Forbidden West.

nvapi: Guard against null device in Reflex calls

---

src/d3d/nvapi_d3d_low_latency_device.cpp
src/util/util_env.cpp

This game gets into an stack overflow after enabling DLSS, the reason is unfortunately unknown.

Spoof Pascal for War Thunder

---

src/sysinfo/nvapi_adapter.cpp
src/util/util_version.h
tests/main.cpp
tests/meson.build
tests/util.cpp

Unfortunately we cannot just use the newer Vulkan macros since the major version for the NVIDIA driver needs 10 bits whereas the newer Vulkan macro for the major version truncates to 7 bits.
From `vulkan_core.h`:
```c++
// DEPRECATED: This define is deprecated. VK_API_VERSION_MAJOR should be used instead.
#define VK_VERSION_MAJOR(version) ((uint32_t)(version) >> 22U)
#define VK_API_VERSION_MAJOR(version) (((uint32_t)(version) >> 22U) & 0x7FU)
```
The newer `VK_API_VERSION_MAJOR` cuts after 7 bits due to introduction of the `variant` number, this conflicts with the 10 bits needed for the NVIDIA major version.
Inspired by https://github.com/doitsujin/dxvk/pull/4001

sysinfo: Replace deprecated Vulkan macros

---

src/nvapi.cpp
src/nvapi_interface.cpp
tests/nvapi_sysinfo_topo.cpp

This is needed to get the NVIDIA Tech demo "Apollo 11 Lunar Landing Demo" running. Downloaded from here: 
https://us.download.nvidia.com/downloads/cool_stuff/demos/Setup-Apollo-11-(1.05).exe

Implement NvAPI_GetAssociatedNvidiaDisplayHandle

---

src/nvapi.cpp
src/nvapi_interface.cpp
tests/nvapi_sysinfo_topo.cpp

Side product while looking into https://github.com/jp7677/dxvk-nvapi/issues/174

nvapi: Add NvAPI_GetLogicalGPUFromDisplay

---

src/nvapi.cpp
src/nvapi_d3d.cpp
src/nvapi_d3d11.cpp
src/nvapi_d3d12.cpp
src/nvapi_disp.cpp
src/nvapi_drs.cpp
src/nvapi_gpu.cpp
src/nvapi_mosaic.cpp
src/nvapi_sys.cpp
src/util/util_log.cpp
src/util/util_statuscode.h

Took a look at our logging,  with this PR it looks like:
ACC startup and benchmark run.
<details>
<summary>dxvk-nvapi-log</summary>
```syslog
---------- 2024-05-31 16:53:01 ----------
dxvk-nvapi:0308:0312:NvAPI_QueryInterface (0xad298d3f): Unknown function ID
dxvk-nvapi:0308:0312:NvAPI_Initialize: Enter
dxvk-nvapi:0308:0312:DXVK-NVAPI v0.7.0-23-g107f990 (AC2-Win64-Shipping.exe)
dxvk-nvapi:0308:0312:Successfully acquired Vulkan vkGetInstanceProcAddr @ 0x6ffffbc1d310
dxvk-nvapi:0308:0312:Successfully loaded nvml.dll
dxvk-nvapi:0308:0312:NVML loaded and initialized successfully
dxvk-nvapi:0308:0312:NvAPI Device: NVIDIA GeForce RTX 3090 (555.42.2)
dxvk-nvapi:0308:0312:NvAPI Output: \\.\DISPLAY1
dxvk-nvapi:0308:0312:<-NvAPI_Initialize: OK
dxvk-nvapi:0308:0312:NvAPI_QueryInterface (0x33c7358c): …
```

Improve logging

---

README.md
src/d3d/lfx.cpp
src/d3d/nvapi_d3d_instance.cpp
src/d3d12/nvapi_d3d12_device.cpp
src/nvapi.cpp
src/nvapi_d3d.cpp
src/nvapi_d3d11.cpp
src/nvapi_d3d12.cpp
src/nvapi_disp.cpp
src/nvapi_drs.cpp
src/nvapi_gpu.cpp
src/nvapi_interface.cpp
src/nvapi_mosaic.cpp
src/nvapi_sys.cpp
src/resource_factory.cpp
src/sysinfo/nvapi_adapter.cpp
src/sysinfo/nvapi_adapter_registry.cpp
src/sysinfo/nvapi_output.cpp
src/sysinfo/nvml.cpp
src/util/util_env.cpp
src/util/util_latency_marker_code.h
src/util/util_log.cpp
src/util/util_log.h
src/util/util_op_code.h
src/util/util_statuscode.h
src/util/util_string.h
tests/util.cpp

~just briefly tested and for actual tracing we should also log all input parameters (wine like, thus only primitives and pointer addresses). Have to think about how to do this elegantly without wasting cycles when tracing is disabled.~
Closes #180 
cc: @SveSop

Add tracing

---

src/nvapi_d3d12.cpp
tests/nvapi_d3d12.cpp

Return politely that we have no meta commands. Need to find a few titles though to verify that no one calls create-metacommand after this.   
cc: @SveSop

d3d12: Improve NvAPI_D3D12_EnumerateMetaCommands

---

src/d3d/nvapi_d3d_low_latency_device.cpp
src/d3d/nvapi_d3d_low_latency_device.h
src/nvapi_d3d12.cpp
tests/nvapi_d3d12.cpp

This lets us avoid having to `QueryInterface` on every call to `NvAPI_D3D12_SetAsyncFrameMarker`. The consequence of doing it like this is that now there might be multiple entries in `m_lowLatencyDeviceMap` pointing to the same `ID3DLowLatencyDevice` so in order to still correctly have a single frame ID generator per `ID3DLowLatencyDevice`, their map is now keyed on low latency devices which we have to retrieve on every call anyway.
We could further reduce the lookups if we either returned intermediate `ID3DLowLatencyDevice` from `SupportsLowLatency` and then acted on it in the following call or if we just got rid of explicit `SupportsLowLatency` and had methods like `SetFrameMarker` returned more detailed error codes (or just `NvAPI_Status` directly). But that's an idea for another day.

Try to improve Reflex command queue lookups

---

src/util/util_env.cpp

See https://github.com/HansKristian-Work/vkd3d-proton/issues/2008 and https://github.com/ValveSoftware/Proton/issues/7735#issuecomment-2136100714 for the background and descriptions of the issue this change aims to resolve.

util: Spoof Ada and later GPUs as Ampere for Ghost of Tsushima

---

README.md
src/nvapi_gpu.cpp
src/nvapi_private.h
src/sysinfo/nvapi_adapter.cpp
src/util/util_env.cpp
src/util/util_env.h

As Ghost of Tsushima recently proved to us, it might be beneficial to have some ability to control reported GPU Arch to games without having to modify the source code and rebuild each time.
Not sure if this is how it should be implemented though, it might be preferable to have all this extracted to some `NV_GPU_ARCHITECTURE_ID env::getGpuArchOverride()` method instead.

Allow overriding GPU Architecture using environment variable

---

src/nvapi_d3d12.cpp
src/sysinfo/nvapi_adapter.h
tests/nvapi_d3d12.cpp

For Turing+ only.
I'm tempted to report those two also for Turing+.
Since there are no `NvAPI_D3D12` equivalents to `NvAPI_D3D11_RSSetExclusiveScissorRects` or  `NvAPI_D3D11_RSSetViewportsPixelShadingRates` I guess those capabilities refer to D3D12 core functionalities, but should do some research into it first. 
Reporting those probably makes no difference in practice.

d3d12: Report other capabilities

---

.clang-tidy-ignore
src/nvapi_d3d11.cpp
src/nvapi_disp.cpp
src/nvapi_gpu.cpp
tests/nvapi_d3d11.cpp

Based on logs of `NvAPI_GPU_GetMemoryInfo` usage, structs can and will be reused. The one's where we zero'ed the struct version are probably not of that category, but lets be consistent and safe everywhere.
TODO:

Ensure that we don't lose struct version

---

README.md
src/nvapi_interface.cpp
src/nvapi_private.h
src/util/util_string.cpp
src/util/util_string.h
tests/util.cpp

Includes some C++ concepts fun, hopefully not too crazy but I wanted the string splitting helper to be fairly generic. Interestingly, I found it easier to do with regex-based separators than matching plain substrings or single characters.
Testing this automatically is a bit tricky because entrypoints are cached, and so is the processed variable value, and I'm kinda afraid it would interfere with other tests. Any ideas, or are you fine with no tests for this thing?

Allow disabling entrypoints by name via environment variable

---

.github/workflows/build-llvm.yml
.gitignore
build-win32-llvm.txt
build-win64-llvm.txt

Wasn't as terrible as I expected but I still wasted a lot of time fighting Meson's nonsense (for example, when I tried choosing the linker using more idiomatic `cpp_ld = 'lld-link'` it insisted on passing `-fuse-ld=lld-link` _to the linker_, which at this point `clang-cl` already determined it to be default `link.exe`, which of course doesn't exist).
TODO: ~~Persist the toolchain flavor in logged version string?~~ Perhaps ~~build and~~ run tests as well? But that's something for another day I think.

LLVM builds (against Windows SDK)

---

inc/nvml.h
version.h.in

As is tradition.
R565 NVAPI brings us a new potentially interesting entrypoint, `NvAPI_D3D11_SetAsyncFrameMarker`. No implementation for now but updating the headers will at least warn us when something attempts to use it.

Update NV headers to R565

---

src/util/util_env.cpp

This reverts commit f86f56b24737d117098a80133516edfb553fe39a.
To be merged after DLSS FG support is in place. Let me know if I should actually write a new commit message.

Revert "util: Spoof Ada and later GPUs as Ampere for Ghost of Tsushima"

---

src/nvapi_private.h

That's all we need.
Originated from the first NVOF PR where that include was used in `nvofapi_image.h`. Good idea to use overall.

nvapi: Include vulkan_core.h

---

src/nvofapi/nvofapi_d3d12_instance.cpp

Needed for older versions of nvngx_dlssg.dll where OF buffer registration was synchronized with GPU work.

NvOFInstanceD3D12: Implement input/output fence points

---

src/nvapi/nvapi_d3d_low_latency_device.cpp
src/nvapi/nvapi_d3d_low_latency_device.h
src/nvapi_d3d.cpp
src/nvapi_d3d12.cpp
tests/nvapi_d3d.cpp
tests/nvapi_d3d12.cpp

Unfortunately `NV_LATENCY_MARKER_TYPE` doesn't match `VkLatencyMarkerNV`, so we need to convert manually. Silently acknowledge, but ignore, calls with unsupported values.
cc: @esullivan-nvidia

nvapi-d3d: Fix NV_LATENCY_MARKER_TYPE forwarding

---

src/meson.build
src/util/util_log.cpp
tests/meson.build

Running the tests produces:
```
6627.084:011c:0120:info:nvapi64-tests:DXVK-NVAPI v0.7.1-101-gee9c8fd+ NVAPI gcc 13.1.0 x86_64 release (nvapi64-tests.exe)
```

util: Log build target name

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
src/util/util_log.cpp

So write to nvapi.log, nvapi64.log and nvofapi64.log separately.

util: Use build target name as log file name

---

src/util/util_env.cpp

See the discussion in our LGD channel.

util: Spoof Ada and later GPUs as Ampere for The Great Circle

---

src/meson.build
src/nvapi/nvapi_adapter.cpp
src/nvapi/nvapi_adapter.h
src/nvapi/nvapi_adapter_registry.cpp
src/nvapi/nvapi_adapter_registry.h
src/nvapi/resource_factory.cpp
src/nvapi/resource_factory.h
src/nvapi/vk.cpp
src/nvapi/vk.h
tests/meson.build
tests/mock_factory.h
tests/nvapi_d3d.cpp
tests/nvapi_d3d11.cpp
tests/nvapi_d3d12.cpp
tests/nvapi_sysinfo.cpp
tests/nvapi_sysinfo_hdr.cpp
tests/nvapi_sysinfo_mocks.h
tests/nvapi_sysinfo_nvml.cpp
tests/nvapi_sysinfo_topo.cpp
tests/resource_factory_util.cpp
tests/resource_factory_util.h

Also gets rid of our custom `VkStructure` used in tests in favor of `VkBaseOutStructure` provided by Vulkan headers.
`MockFactory` currently does not override new factory overload, I left this for later, when it's actually used in tests.
Should I also rename `ResourceFactory::CreateVulkan` to `ResourceFactory::CreateVk`?

nvapi: Rename Vulkan → Vk and rework its construction

---

README.md
src/nvapi/nvapi_adapter.cpp
src/nvapi/nvapi_adapter.h
src/nvapi_d3d12.cpp
src/nvapi_gpu.cpp
src/nvapi_private.h
src/util/util_env.cpp
tests/nvapi_d3d12.cpp
tests/nvapi_sysinfo.cpp
tests/nvapi_system.cpp
tests/resource_factory_util.cpp
tests/resource_factory_util.h

Follow up on #239 
cc: @liam-middlebrook

Add GB20x Support to NvAPI_GPU_GetArchInfo (follow up)

---

src/interfaces/dxvk_interfaces.h
src/nvapi_interface.cpp

Might be a bit heavy-handed but `insert`s can cause rehashing to occur and (afaiu) because of it it's not safe to read from the map during this time on another thread.
Maybe some rwlock would make more sense? Not sure. To be reconsidered it it causes performance problems.

nvapi: Guard interface registry lookups with a mutex

---

src/meson.build
src/nvofapi_cuda.cpp
src/nvofapi_entrypoints.h
tests/meson.build
tests/nvofapi_cuda.cpp
tests/nvofapi_main.cpp
tests/nvofapi_tests_private.h

This will return an error with a logtext indicating to upgrade DLSS version since the new DLSS4 version do not use opticalflow for DLSS anymore ref NVIDIA

nvofapi: NvOFAPICreateInstanceCuda - stub

---

src/meson.build
src/nvofapi64.def
src/nvofapi_cuda.cpp
src/nvofapi_d3d11.cpp
src/nvofapi_d3d12.cpp

This will make the nvofapi64.dll binary export only the used symbols, and make it similar to the windows version.
The usage of __cdecl for the calls SHOULD not be needed, as the `nvOpticalFlowCommon.h` header spesifically sets this:
```
#ifdef _WIN32
#define NVOFAPI __stdcall
#else
#define NVOFAPI
#endif
```
Testing on the OpticalFlow SDK samples, it seems to work as intended. Lets have a talk about that :+1: 
The exported symbols is then like this when using winedump -j export
```
Name:            nvofapi64.dll
Characteristics: 00000000
TimeDateStamp:   679FAE1F Sun Feb  2 18:40:47 2025
Version:         0.00
Ordinal base:    1
Functions RVA:   0014B028
Ordinals RVA:    0014B050
Names RVA:       0014B03C
Entry Pt  Ordn  Name
00029DF0     1  NvOFAPICreateInstanceCuda
00017150     2 …
```

nvofapi: Only export used symbols

---

src/util/util_string.cpp

Weird how GitHub Actions didn't catch it…

util: Avoid using std::string_view::starts_with

---

src/nvapi.cpp
src/nvapi_sys.cpp
version.h.in

Only place I ever saw this being used in an actual title:

nvapi: Use NVAPI_SDK_VERSION

---

.gitignore
src/nvapi/nvapi_d3d_low_latency_device.cpp
src/nvapi/nvapi_d3d_low_latency_device.h
tests/nvapi_d3d.cpp

Not tested ...
Based on https://github.com/HansKristian-Work/vkd3d-proton/issues/2294

Drop repeated frame IDs

---

src/nvapi/nvapi_d3d11_device.cpp
src/nvapi/nvapi_d3d11_device.h
src/nvapi/nvapi_d3d12_device.cpp
src/nvapi/nvapi_d3d12_device.h
tests/nvapi_d3d11.cpp
tests/nvapi_d3d12.cpp

Follow up from earlier D3D11 and D3D12 rework.

nvapi-d3d11/12: Check for VK_NVX_image_view_handle

---

README.md
src/nvapi.cpp
src/util/util_ngx_debug.h
src/util/util_string.cpp
src/util/util_string.h
tests/util.cpp

Example:
~`DXVK_NVAPI_SET_DLSS_INDICATOR=1024 DXVK_NVAPI_SET_DLSSG_INDICATOR=2`~
~`DXVK_NVAPI_SET_NGX_INDICATOR=DLSS=1024,DLSSG=2`~
`DXVK_NVAPI_SET_NGX_DEBUG_OPTIONS=DLSSIndicator=1024,DLSSGIndicator=2,Logging=1,LogLevel=1`
Probably out of scope...
Reference:
- https://github.com/NVIDIA/DLSS/tree/main/utils
- https://github.com/NVIDIAGameWorks/Streamline/blob/main/docs/ProgrammingGuideDLSS_G.md#200-dlss-fg-indicator-text

nvapi: Allow switching NGX registry settings

---

src/util/util_env.cpp

This reverts commit c29f6f0bef8f0d6122ce9346ccc95ec2fb3da701.
The workaround is no longer needed after title Update 3.

Revert "util: Spoof Ada and later GPUs as Ampere for The Great Circle"

---

src/nvapi_d3d.cpp
src/util/util_statuscode.h
tests/nvapi_d3d.cpp

Fallout New Vegas seems to think it's running on an SLI system unless we just error out here.
I also tried setting `maxNumAFRGroups` and `numAFRGroups` both to 0 but that didn't fix it either.
Additionally I tried just setting `numAFRGroups` to 0 and keeping `maxNumAFRGroups` at 1 but that didn't work either.
The Nvidia sample suggests what we have right now is a valid implementation:
`bSLIEnabled = (gMaxNumAFRGroups > 1);` but it appears that the check in Fallout isn't particularly robust.
So I suggest we just return an error when the function gets called. Alternatively we could return null pointers for the SLI functions in `QueryInterface`. I don't have a test setup for Nvapi on Windows right now, so I can't check what Nvidia does on Windows these days without a lot of effort.
Fixes: …

nvapi-d3d: Just error out of GetCurrentSLIState

---

README.md

cc @Saancreed since I'm reusing most from https://github.com/jp7677/dxvk-nvapi/issues/254 in the wki page (https://github.com/jp7677/dxvk-nvapi/wiki/Passing-driver-settings)

meta: Add DRS wiki link

---

src/nvapi/nvapi_adapter.cpp
src/nvapi/nvapi_adapter.h
src/nvapi_d3d12.cpp
tests/nvapi_d3d12.cpp

Lets be prepared for wine versions that don't support VK_NV_cuda_kernel_launch, see https://gitlab.winehq.org/wine/wine/-/merge_requests/7743
BW version taken from https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/34331

nvapi-d3d12: Add SM version fallback

---

src/nvapi/nvapi_adapter.cpp
src/nvapi/nvapi_adapter.h
src/nvapi_d3d12.cpp
src/nvapi_vulkan.cpp
tests/nvapi/resource_factory_util.cpp
tests/nvapi/resource_factory_util.h
tests/nvapi_d3d12.cpp

Newer Vulkan headers hide this extension behind the `VK_ENABLE_BETA_EXTENSIONS` define. Remove this for now and always use our fall-back. This won't make a difference in practise since this extension was already excluded from newer Winevulkan versions.
~This PR unfortunately depends on https://github.com/misyltoad/vkroots/issues/13 and thus also misses a `vkroots` sub module update.~
Closes #296

Remove VK_NV_cuda_kernel_launch usage

---

src/nvapi/low_latency_frame_id_generator.cpp
src/nvapi/low_latency_frame_id_generator.h
src/nvapi/nvapi_d3d_low_latency_device.cpp
tests/nvapi_d3d.cpp

With frame generation apps will send multiple OUT_OF_BAND_PRESENT markers for a given frameID. This lets the Nvidia driver know that frame gen is happening.
dxvk-nvapi currently discards all but the first OUT_OF_BAND_PRESENT marker. This change removes that logic and passes through all of the app's markers.
Tested by running Cyberpunk 2077 with 4x frame generation and logging the markers received by the Nvidia driver. Originally we only saw one VK_LATENCY_MARKER_OUT_OF_BAND_PRESENT_START_NV marker per frameID. With this change we see four.

Allow multiple of the same latency marker for a given frameID
