- .github/workflows/artifacts.yml
Direct copy from https://github.com/doitsujin/dxvk/blob/master/.github/workflows/artifacts.yml since we are doing more or less the same.
> Add github action.

- src/meson.build
- src/sysinfo/nvapi_adapter.cpp
- src/sysinfo/nvapi_adapter.h
- src/sysinfo/nvapi_adapter_registry.cpp
- src/sysinfo/nvapi_adapter_registry.h
- src/sysinfo/vulkan.cpp
- src/sysinfo/vulkan.h
Not sure yet if this improves code quality.
> Extract some vulkan code into separate class.

- inc/nvml.h
- src/meson.build
- src/nvapi_gpu.cpp
- src/nvapi_interface.cpp
- src/nvapi_private.h
- src/sysinfo/nvapi_adapter.cpp
- src/sysinfo/nvapi_adapter.h
- src/sysinfo/nvapi_adapter_registry.cpp
- src/sysinfo/nvapi_adapter_registry.h
- src/sysinfo/nvml.cpp
- src/sysinfo/nvml.h
- src/sysinfo/vulkan.cpp
- src/sysinfo/vulkan.h
- src/util/util_statuscode.h
Based on https://github.com/jp7677/dxvk-nvapi/pull/15
This addresses https://github.com/jp7677/dxvk-nvapi/issues/5
> Add support for NVIDIA Management Library v2

- src/nvapi_gpu.cpp
- src/nvapi_interface.cpp
- src/sysinfo/nvapi_adapter.cpp
- src/sysinfo/nvapi_adapter.h
- src/sysinfo/nvml.cpp
- src/sysinfo/nvml.h
This grabs bios version from nvml for the graphics adapter.
> Add function for NvAPI_GPU_GetVbiosVersionString

- README.md
Resolves https://github.com/jp7677/dxvk-nvapi/issues/26
> meta: Update readme

- src/d3d12/nvapi_d3d12_device.cpp
- src/d3d12/nvapi_d3d12_device.h
Signed-off-by: Roshan Chaudhari <rochaudhari@nvidia.com>
> nvapi-d3d12: add caching for ID3D12GraphicsCommandListExt

- src/d3d11/nvapi_d3d11_device.cpp
- src/d3d11/nvapi_d3d11_device.h
- src/d3d12/nvapi_d3d12_device.cpp
- src/d3d12/nvapi_d3d12_device.h
Signed-off-by: Roshan Chaudhari <rochaudhari@nvidia.com>
> nvapi-d3d12, nvapi-d3d11: add locks for handling caching maps

- README.md
- src/sysinfo/nvapi_adapter.cpp
- tests/nvapi_d3d12.cpp
- tests/nvapi_sysinfo.cpp
- tests/nvapi_sysinfo_util.cpp
Keep the old behavior behind and environment variable. 
Resolves https://github.com/jp7677/dxvk-nvapi/issues/58
> Default to nvidia only

- package-release.sh
- src/nvapi_drs.cpp
- src/nvapi_interface.cpp
- src/nvapi_static.h
- src/util/util_statuscode.h
- src/util/util_string.cpp
- src/util/util_string.h
- tests/main.cpp
- tests/nvapi_drs.cpp
- tests/nvapi_tests.cpp
Those methods doesn't do anything, it just looks prettier in the logs.
> Add some Nvidia DRS methods

- .github/workflows/artifacts.yml
Addresses https://github.com/jp7677/dxvk-nvapi/issues/73
> github: Add workflow for building releases based on tags

- .github/workflows/artifacts.yml
So really just the output is missing, the tests are running just fine and the pipeline fails when a test fails.  
This addresses https://github.com/jp7677/dxvk-nvapi/issues/80
> Fix test output on GitHub workflow

- .github/workflows/artifacts.yml
Unfortunately we have to do this manually since the GitHub upload action only supports zips.
> github: Create release tarballs on GitHub

- .github/workflows/artifacts.yml
Restore test execution in GitHub actions.
> Restore test execution on CI

- src/nvapi.cpp
- src/nvapi_interface.cpp
- tests/nvapi_sysinfo_topo.cpp
Implement NVAPI_GetLogicalGPUFromPhysicalGPU as the inverse of NVAPI_GetPhysicalGPUsFromLogicalGPU.
> Implement NVAPI_GetLogicalGPUFromPhysicalGPU

- src/nvapi.cpp
- src/nvapi_interface.cpp
- src/nvapi_sys.cpp
- tests/nvapi_sysinfo.cpp
- tests/nvapi_system.cpp
Supersedes https://github.com/jp7677/dxvk-nvapi/pull/131
Slightly improved and includes tests.
cc: @SveSop
> Implement NvAPI_SYS_GetDisplayDriverInfo

- meson.build
This mirrors https://github.com/doitsujin/dxvk/commit/2ef41bdbf6841c2887e7af4b7c3b26235d3e7efa and also makes the meson setup again more like DXVK.
> build: Switch symbols to DWARF 4

- src/nvapi_gpu.cpp
- src/util/util_env.cpp
> Fake GPU query success for Xdefiant

- inc/nvml.h
> includes: Update NVML header to R560

- src/nvapi_gpu.cpp
- tests/nvapi_sysinfo.cpp
- tests/nvapi_sysinfo_nvml.cpp
Only NvAPI_GPU_GetMemoryInfoEx wants bytes.
> nvapi-gpu: Report size in KB for NvAPI_GPU_GetMemoryInfo

- inc/catch_amalgamated.cpp
- inc/catch_amalgamated.hpp
- tests/mock_factory.h
- tests/nvapi_d3d.cpp
- tests/nvapi_d3d11.cpp
- tests/nvapi_d3d12.cpp
- tests/nvapi_sysinfo.cpp
- tests/nvapi_sysinfo_hdr.cpp
- tests/nvapi_sysinfo_nvml.cpp
- tests/nvapi_sysinfo_topo.cpp
- tests/resource_factory_util.cpp
- tests/resource_factory_util.h
Finally again nice test failures without crashes or exceptions.
Closes #203
> Fix C<*> mocks lifetime in tests

- src/nvapi_gpu.cpp
No need to check struct version twice
> nvapi-gpu: Simplify check

- src/nvapi_interface.cpp
- src/nvapi_private.h
- src/util/util_string.h
Mingw used for Proton builds does not fully support C++20 features.
> Fix Proton CI

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
Some words to clarify the meaning of the tweaks.
> Issue template and readme improvements

- src/nvapi/nvapi_adapter_registry.cpp
- src/nvapi/nvapi_d3d11_device.cpp
- src/nvapi/nvapi_d3d11_device.h
- src/nvapi/nvapi_d3d12_device.cpp
- src/nvapi/nvapi_d3d12_device.h
- src/nvapi/nvapi_d3d_low_latency_device.cpp
- src/nvapi/nvapi_d3d_low_latency_device.h
- src/nvapi/nvapi_vulkan_low_latency_device.cpp
- src/nvapi/nvapi_vulkan_low_latency_device.h
- src/nvapi/vk.cpp
- src/nvapi/vk.h
- src/nvapi_vulkan.cpp
- tests/main.cpp
- tests/meson.build
- tests/mock_factory.h
- tests/nvapi_d3d11.cpp
- tests/nvapi_d3d12.cpp
- tests/nvapi_sysinfo.cpp
- tests/nvapi_sysinfo_hdr.cpp
- tests/nvapi_sysinfo_mocks.h
- tests/nvapi_sysinfo_nvml.cpp
- tests/nvapi_sysinfo_topo.cpp
- tests/nvapi_tests_private.h
- tests/nvapi_vulkan.cpp
- tests/nvapi_vulkan_mocks.h
- tests/resource_factory_util.cpp
- tests/resource_factory_util.h
- tests/util.cpp
> Add VK-Reflex tests

- README.md
- src/nvapi_drs.cpp
- src/nvapi_private.h
- src/util/util_string.cpp
- src/util/util_string.h
- tests/nvapi_drs.cpp
- tests/util.cpp
Just an idea for now, let me know what you think about it.
> Implement some DRS stuff

- src/nvofapi/nvofapi_vk_instance.cpp
- tests/mocks/vulkan_mocks.h
- tests/nvofapi_vk.cpp
Follow up from https://github.com/jp7677/dxvk-nvapi/pull/249#discussion_r1936094545
> nvofapi-vk: Check VK_NV_optical_flow availability

- src/meson.build
- src/nvofapi_d3d11.cpp
- src/nvofapi_private.h
- tests/meson.build
- tests/nvofapi_cuda.cpp
- tests/nvofapi_d3d11.cpp
- tests/nvofapi_main.cpp
Add stub for NvOFAPICreateInstanceD3D11 and fix a couple of typos in tests for NvOFAPICreateInstanceCuda
> Nvofapi d3d11

- inc/nvml.h
Changes nothing, just a feel good PR.
> Update NVML/Vulkan headers

- src/nvapi_drs.cpp
Changes initial log lines from:
```
5646.663:0170:0174:info:nvapi64-tests:DXVK_NVAPI_DRS_SETTINGS is set, applying the following DRS settings when requested by the application (2 total):
5646.663:0170:0174:info:nvapi64-tests:    0x10e41df3 = 0xffffff
5646.663:0170:0174:info:nvapi64-tests:    0x10e41e01 = 0x1
```
to
```
5646.663:0170:0174:info:nvapi64-tests:DXVK_NVAPI_DRS_SETTINGS is set, applying the following DRS settings when requested by the application (2 total):
5646.663:0170:0174:info:nvapi64-tests:    0x10e41df3/Override DLSS-SR presets = 0xffffff
5646.663:0170:0174:info:nvapi64-tests:    0x10e41e01/Enable DLSS-SR override = 0x1
```
Unfortunately we need to iterate twice over `mapSettingDWORD` when a setting was declared, but I guess not overly dramatic since this isn't on a hot …
> nvapi-drs: Log known declared setting names

- package-release.sh
- src/meson.build
- src/nvapi_interface.cpp
- src/nvapi_ngx.cpp
- src/util/util_log.h
- tests/meson.build
- tests/nvapi_main.cpp
- tests/nvapi_ngx.cpp
- tests/util.cpp
Just boilerplate and some guesswork... So not sure yet if this behaves nicely in reality.
> nvapi-ngx: Stub Get/SetNGXOverrideState

- README.md
- src/meson.build
- src/nvapi_drs.cpp
- src/util/util_drs.cpp
- src/util/util_drs.h
- tests/meson.build
- tests/nvapi_drs.cpp
- tests/util.cpp
Please forgive the macro horrors, C++ truly lacks some kind of compile-time reflection…
TODO: tests and README updates…
> DRS (NGX) settings for human beings

- src/meson.build
- src/nvapi/low_latency_frame_id_generator.cpp
- src/nvapi/low_latency_frame_id_generator.h
- src/nvapi/nvapi_d3d_low_latency_device.cpp
- src/nvapi/nvapi_d3d_low_latency_device.h
- src/nvapi_d3d.cpp
- src/nvapi_d3d12.cpp
- tests/meson.build
- tests/nvapi_d3d.cpp
- tests/nvapi_d3d12.cpp
~First iteration.~ Compiles and tests are green. Also tested briefly with GoW and CP2077. Nvapi logs looked normal and DXVK HUD showed sleep times.
> nvapi-d3d: Rework NvapiD3dLowLatencyDevice

- src/nvapi/nvapi_d3d11_device.cpp
- src/nvapi/nvapi_d3d11_device.h
- src/nvapi/nvapi_d3d_low_latency_device.cpp
- src/nvapi/nvapi_d3d_low_latency_device.h
- src/nvapi/nvapi_vulkan_low_latency_device.cpp
- src/nvapi/nvapi_vulkan_low_latency_device.h
- src/nvapi_d3d11.cpp
- tests/nvapi_d3d11.cpp
~Only green tests for now.~ I haven't seen any regression in GoW nor ACC. Logs looked nice.
> Rework NvapiD3D11Device

- src/meson.build
- src/nvapi/nvapi_d3d11_device.h
- src/nvapi/nvapi_d3d12_command_queue.cpp
- src/nvapi/nvapi_d3d12_command_queue.h
- src/nvapi/nvapi_d3d12_device.cpp
- src/nvapi/nvapi_d3d12_device.h
- src/nvapi/nvapi_d3d12_graphics_command_list.cpp
- src/nvapi/nvapi_d3d12_graphics_command_list.h
- src/nvapi/nvapi_d3d_low_latency_device.h
- src/nvapi_d3d12.cpp
- tests/meson.build
- tests/nvapi/resource_factory_util.cpp
- tests/nvapi_d3d12.cpp
- tests/nvapi_tests_private.h
Seems to work, but yet happy with this one ....
> Rework NvapiD3D12Device

- src/nvapi/nvapi_d3d11_device.cpp
- src/nvapi/nvapi_d3d11_device.h
- src/nvapi/nvapi_d3d12_command_queue.cpp
- src/nvapi/nvapi_d3d12_command_queue.h
- src/nvapi/nvapi_d3d12_device.cpp
- src/nvapi/nvapi_d3d12_device.h
- src/nvapi/nvapi_d3d12_graphics_command_list.cpp
- src/nvapi/nvapi_d3d12_graphics_command_list.h
- src/nvapi/nvapi_d3d_low_latency_device.cpp
- src/nvapi/nvapi_d3d_low_latency_device.h
- src/nvapi_d3d.cpp
- src/nvapi_d3d11.cpp
- src/nvapi_d3d12.cpp
- tests/nvapi_d3d11.cpp
- tests/nvapi_d3d12.cpp
Follow up from earlier refactorings.
> Handle HRESULT's from calls deeper into the stack

- tests/nvapi_d3d11.cpp
- tests/nvapi_d3d12.cpp
- tests/nvapi_system.cpp
Use check for places where we don't want to bail out immediately.
> tests: Use CHECK more often
